package:
  name: gfortran
  version: 4.9.3

source:
  fn: gcc-4.9.3.tar.bz2
  url: http://gnu.mirrors.hoobly.com/gnu/gcc/gcc-4.9.3/gcc-4.9.3.tar.bz2
  #md5: a51bcfeb3da7dd4c623e27207ed43467

build:
  detect_binary_files_with_prefix: true
  number: 1

requirements:
  build:
    - gmp >=4.3.2
    - mpfr >=2.4.2
    - mpc >=0.8.1
    - isl <=0.14
    - cloog 0.18.0
  run:
    - gmp >=4.2
    - mpfr >=2.4.0
    - mpc >=0.8.0
    - isl <=0.14
    - cloog 0.18.0

about:
  home: http://gcc.gnu.org/
  summary: The GNU Compiler Collection
  license: GPL

