package:
  name: shapely
  version: 1.5.7

source:
  git_url: https://github.com/Toblerity/Shapely.git
  git_tag: 1.5.7
  patches:
    - geos_c.win.patch      # [win]

build:
  number: 0

requirements:
  build:
    - python
    - geos >=3.4
    - cython
    - numpy
  run:
    - python
    - geos
    - numpy

test:
  imports:
    - shapely
    - shapely.speedups._speedups

about:
  home: https://github.com/Toblerity/Shapely
  license: BSD
  summary: 'Python package for manipulation and analysis of geometric objects in the Cartesian plane'
